#!/usr/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Wallpaper Switcher
# @vicinae.mode compact

find ~/Pictures/Wallpapers -type f | vicinae dmenu -p "Pick a Wallpaper" | xargs -I {} sh -c 'awww img "{}" && ln -sf "{}" ~/.cache/current_wallpaper'
